loki:
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 3
    storage:
      bucketNames:
        chunks: k8s-loki-chunks-5bksa
        ruler: k8s-loki-ruler-5bksa
      type: s3
      s3:
        s3ForcePathStyle: false
        insecure: false
        region: eu-central-1
  singleBinary:
    replicas: 3
    persistence:
      enabled: false
    extraVolumes:
      - name: bolt-db
        emptyDir: {}
    extraVolumeMounts:
      - name: bolt-db
        mountPath: /var/loki
  monitoring:
    selfMonitoring:
      enabled: true
      grafanaAgent:
        installOperator: false